name: "âœ… Linter"

# CINTENT >> MANUAL_TRIGGER
# on:
#   push:
#     branches:
#       - master
#     paths:
#       - '**.py'
#   pull_request:
#     branches:
#       - master
#     paths:
#       - '**.py'
#   workflow_dispatch:
on: [repository_dispatch, workflow_dispatch]

env:
  PROJECT_FOLDER: "LoopStructural"
  PYTHON_VERSION: 3.9

jobs:
  lint-py:
    name: Python ðŸ

    runs-on: ubuntu-latest

    steps:
      - name: Get source code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          # cache: "pip"
          python-version: ${{ env.PYTHON_VERSION }}

      # CINTENT >> INSERT_CINTENT
      - uses: JavidDitty/setup-cintent@64faaac1333aabc2e0a00af6109b48ec4d8071bf

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install black ruff

      - name: Autoformat with black
        run: |
          black .

      - name: Lint with ruff
        run: |
          ruff check ${{env.PROJECT_FOLDER}} --fix

      # CINTENT >> INSERT_CINTENT
      - name: Upload CIntent Artifacts
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: ${{ env.CINTENT_ARTIFACT_NAME }}
          path: ${{ env.CINTENT_LOGS }}

      # CINTENT >> REMOVE_PRECOMMIT
      # - uses: stefanzweifel/git-auto-commit-action@v5
      #   with:
      #     push_options: --force
      #     commit_message: "style: style fixes by ruff and autoformatting by black"
